import { InferGetServerSidePropsType } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Token } from "./api/token";

export const getServerSideProps = async () => {
  const tokenResult = await fetch("/api/token");
  const token: Token = await tokenResult.json();

  return {
    props: { token }, // will be passed to the page component as props
  };
};

const Home = ({
  token,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Example embedding Cumulio</p>
          <pre>{JSON.stringify(token, null, 2)}</pre>
        </div>
      </main>
    </>
  );
};

export default Home;
