import { InferGetServerSidePropsType } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Example embedding Cumulio</p>
        </div>
        <div className={styles.grid}>
          <a className={styles.card} href="/normalImport">
            Go To Normal Import Example
          </a>
          <a className={styles.card} href="/esmImport">
            Go To ESM Import Example
          </a>
        </div>
      </main>
    </>
  );
};

export default Home;
